### PR TITLE
added intllib support (with pot catalog files)

### PR DESCRIPTION
**Pull request by fat115**
updated as requested

### CODE REVIEW

**Review by GreenXenith — DISMISSED** [review]
Why do the tabs need to be changed to spaces? Spaces are annoying when trying to edit, and I would like to keep it consistent. Also, tabs are easier to use.

**Comment by fat115** [comment]
In fact, there were some lines in nodes.lua with spaces (lines 235 to 260) so I changed them by tabs to be consistent. I agree that tabs are easier.

**Comment by fat115** [comment]
Oups, I've forgotten to declare S function in batter.lua. That's done.

**Comment by GreenXenith** [comment]
Merged b880be8

**Pull request merged**
